POST http://localhost:3003/api/blogs
Content-Type: application/json

{
   "title": "Ideas on Unit Testing",
   "author": "Alan Hardy",
   "url": "mongodb://ahblog23",
   "likes": "23"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
   "title":"Go To Statement Considered Harmful",
   "author":"Edsger W. Dijkstra",
   "url":"http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
   "likes": "5"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
   "title": "React patterns",
   "author": "Michael Chan",
   "url": "https://reactpatterns.com/",
   "likes": "7"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvdWJ0eTIiLCJpZCI6IjY1ODk4YTUwOGRjNmQ0NDQ0NmIwMTU3NiIsImlhdCI6MTcwMzUzMjkwOCwiZXhwIjoxNzAzNTM2NTA4fQ.yWR-MStOABgrvhVa-Tcakx-5W5Gf5YuRtTdMHkqXuaY

{
   "title": "Type wars",
   "author": "Robert C. Martin",
   "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
   "likes": "2"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvdWJ0eSIsImlkIjoiNjU4OThhNGU4ZGM2ZDQ0NDQ2YjAxNTcxIiwiaWF0IjoxNzAzNTM1MTcxLCJleHAiOjE3MDM1Mzg3NzF9.zIEBFphxXOeY_IBdHiytz7BZt3t5wwkUg85o6JBCnHk

{
   "title": "React patterns",
   "author": "Michael Chan",
   "url": "https://reactpatterns.com/",
   "likes": "7"
}