POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VS code rest client is a pretty handy tool",
    "important": true
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "lol ok",
    "important": false,
    "userId": "658888fa8930d7ef3554d49d"
}

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "root says hey",
    "important": true,
    "userId": "658888968930d7ef3554d498"
}

###
PUT http://localhost:3001/api/notes/658451e91849946f1ed59863
Content-Type: application/json

{
    "content": "HTML is Easy",
    "important": false
}

###
DELETE http://localhost:3001/api/notes/658451e91849946f1ed59864
